-- ============================================================
-- BLOOM RAFFLE · SEDO 72nd Congress Palma de Mallorca 2026
-- Supabase schema + Row Level Security
-- ============================================================
-- Run this in: Supabase Dashboard > SQL Editor
-- ============================================================

-- 1) TABLE
create table if not exists public.raffle_entries (
  id              uuid primary key default gen_random_uuid(),
  entry_number    bigint generated by default as identity unique,
  full_name       text not null,
  email           text not null unique,
  specialization  text not null,
  phone           text not null,
  clinic_name     text,
  country         text,
  created_at      timestamp with time zone default now()
);

-- Helpful indexes
create index if not exists idx_raffle_email
  on public.raffle_entries (lower(email));
create index if not exists idx_raffle_entry_number
  on public.raffle_entries (entry_number);
create index if not exists idx_raffle_created_at
  on public.raffle_entries (created_at desc);


-- 2) ROW LEVEL SECURITY
alter table public.raffle_entries enable row level security;

-- Drop old policies if re-running this script
drop policy if exists "Anonymous can insert raffle entries"      on public.raffle_entries;
drop policy if exists "Authenticated admins can read all"        on public.raffle_entries;
drop policy if exists "Authenticated admins can update entries"  on public.raffle_entries;
drop policy if exists "Authenticated admins can delete entries"  on public.raffle_entries;

-- Public (anon) can ONLY insert. They cannot read anyone else's entry.
create policy "Anonymous can insert raffle entries"
  on public.raffle_entries
  for insert
  to anon
  with check (true);

-- Authenticated admins can read everything
create policy "Authenticated admins can read all"
  on public.raffle_entries
  for select
  to authenticated
  using (true);

-- Authenticated admins can edit/delete (handy at the booth)
create policy "Authenticated admins can update entries"
  on public.raffle_entries
  for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated admins can delete entries"
  on public.raffle_entries
  for delete
  to authenticated
  using (true);


-- 3) RPC: lookup raffle number by email (for re-shows on duplicate submit)
-- This bypasses RLS so anon callers can retrieve their own number after
-- accidentally re-submitting the same email.
create or replace function public.lookup_raffle_number_by_email(p_email text)
returns bigint
language sql
security definer
set search_path = public
as $$
  select entry_number
  from public.raffle_entries
  where lower(email) = lower(p_email)
  limit 1;
$$;

-- Allow anon to call the function
grant execute on function public.lookup_raffle_number_by_email(text) to anon;


-- 3b) RPC: insert a new raffle entry (or return existing number on dup email)
-- This bypasses the "anon can INSERT but not SELECT" RLS gotcha by returning
-- the entry_number from a SECURITY DEFINER function.
create or replace function public.submit_raffle_entry(
  p_full_name       text,
  p_email           text,
  p_specialization  text,
  p_phone           text,
  p_clinic_name     text default null,
  p_country         text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_entry_number bigint;
begin
  if p_full_name is null or p_full_name = ''
     or p_email is null or p_email = ''
     or p_specialization is null or p_specialization = ''
     or p_phone is null or p_phone = '' then
    raise exception 'missing_required_fields';
  end if;

  -- If the email already exists, return its existing entry_number.
  select entry_number into v_entry_number
  from public.raffle_entries
  where lower(email) = lower(p_email)
  limit 1;

  if v_entry_number is not null then
    return v_entry_number;
  end if;

  insert into public.raffle_entries
    (full_name, email, specialization, phone, clinic_name, country)
  values
    (p_full_name, lower(p_email), p_specialization, p_phone, p_clinic_name, p_country)
  returning entry_number into v_entry_number;

  return v_entry_number;
end;
$$;

grant execute on function public.submit_raffle_entry(text, text, text, text, text, text) to anon;


-- ============================================================
-- 4) CREATE THE ADMIN USER
-- ============================================================
-- Do this in: Supabase Dashboard > Authentication > Users > Add user
--   - Type: "Create new user"
--   - Email: your admin email (e.g. info@bloomaligner.fr)
--   - Password: choose a strong password
--   - Auto Confirm User: YES
--
-- That's the email/password you'll use to sign into admin.html.
-- ============================================================


-- ============================================================
-- 5) (OPTIONAL) Quick sanity check — should return 0 right after setup
-- ============================================================
-- select count(*) from public.raffle_entries;
